version: 2
sources:
  - name: raw
    schema: gz_raw_data 
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: we have one product id per orders id
        columns:
            - name: date_date
              description: date when purchased
            - name: orders_id
              description: foreign key to ship
            - name: pdt_id
              description: foreign key to product
            - name: revenue
              description: the amount paid by the customer to purchase the product
            - name: quantity
              description: the quantity of products purchased for this order

      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
              
            
          - name: purchase_price
            description: the purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: ship of GreenWeez
        columns:
          - name: orders_id 
            description: primary key of table
            tests:
              - unique
              - not_null           
          - name: shipping_fee
            description: the price the customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in the warehouse 
          - name: ship_cost
            description: the shipping cost paid by Greenweez to the carrier/transport
    

